### ISSUE TITLE
Missing years in table 222?

### ISSUE THREAD

**Issue by ihrke** [makinin/rdbhapi#10]
When I download data from table 222, the earliest year (`Årstall`) I get is 2015:

```{r}
dbhd.222 <- dbh_data(222)
dbhd.222 |> group_by(Institusjonsnavn) |> summarize(min(Årstall)) |> data.frame()
```

However, there seems to be more data available. When I run the same command with `dbh_data(225)`, I get much earlier data for some universities.

**Comment by ihrke** [comment]
I found the reason: Table 222 goes only back until 2015 (https://dbh.hkdir.no/datainnhold/tabell-dokumentasjon/222). Apparently there was a change in how data was recorded back then. Is it a problem if I use table 225 and sum across the different position types? That should give similar numbers as table 222 but allow to go further back in time, am I right?

**Comment by mni-hkdir** [comment]
These two tables show different things. Table 225 counts employees as full time equivalents (FTE) and can be summed across all dimensions (except year). Table 222 gives a headcount (i.e. distinct people) per organisational unit. Here data starts at 2015, which is when we started collecting data on an individual level. Before 2015 we only have FTE data, not the number of people.


The safest is to use FTE data, which is also fairly standard when e.g. comparing data from Norway with other countries.

**Comment by ihrke** [comment]
Thanks for the info!
