### ISSUE TITLE
Bruke group_by uten filters

### ISSUE THREAD

**Issue by sigve-berge-hofland** [makinin/rdbhapi#2]
Når `filters` er tom, brukes bulknedlasting og andre argumenter ignoreres.
```
dbh_data(101, group_by = list("Årstall"))
```
Gir bare hele tabell 101, uten noen aggregering og uten varsel. I dette tilfellet kunne funksjonen bare lagt inn et filter `all` på en vilkårlig variabel.

**Comment by mni-hkdir** [comment]
Jeg tenkte å bruke jsonlite::stream_in(gzcon(curl("https://api.nsd.no/dbhapitjener/Tabeller/bulk-csv?rptNr=900"))) nen har feil melding opening gzcon input connection.
Error: parse error: trailing garbage
                     "Institusjonskode","Institusjonsnavn","Ã…rstall",
                     (right here) ------^
Bare tenker om litt furter imput av så store data sets

**Comment by mni-hkdir** [comment]
På min github kan du se ny funksjon for laste ned store data DBH_store_data.R.
Det ganske ligne på https://github.com/rOpenGov/eurostat/blob/master/R/get_eurostat_raw.R og data imort går mye fortere.
Det som forstat beskymre meg er at jeg lastet ned tabell 900 som  A tibble: 1,718,518 x 27
